local_repository(
    name = "rules_intellij",
    path = "../../",
)

load("@rules_intellij//intellij:repositories.bzl", "rules_intellij_repositories")
rules_intellij_repositories()

load("@rules_intellij//intellij:deps_repositories.bzl", "rules_intellij_deps_repositories")
rules_intellij_deps_repositories()

load("@rules_intellij//intellij:deps_toolchains.bzl", "rules_intellij_deps_toolchains")
rules_intellij_deps_toolchains()

load("@rules_intellij//intellij:predefined.bzl", "idea_UI_2023_3_2")

idea_UI_2023_3_2()

register_toolchains("//:project")